name: build

on:
  pull_request:
    branches: [ 'main' ]
    paths:
    - .github/workflows/build.yml
    - 'benches/**'
    - 'examples/**'
    - 'src/**'
    - 'tests/**'
    - Cargo.toml

# For passing artifacts between jobs, see
#  https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
jobs:
  prepare-openssl:
    runs-on: ubuntu-latest
    container: 
      image: sammyne/openssl:1.1.1s-ubuntu20.04
    steps:
    - name: Upload the prebuilt openssl
      uses: actions/upload-artifact@v3
      with:
        name: openssl
        path: /opt/openssl
    
  build:
    needs: prepare-openssl
    runs-on: ubuntu-latest
    container: 
      image: rust:1.65.0-bullseye
    steps:
    - name: Download the prebuilt openssl
      uses: actions/download-artifact@v3
      with:
        name: openssl
        path: /opt/openssl
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Rust toolchains
      run: |
        rustc --version &&
        rustup --version &&
        cargo --version
      shell: bash
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Build
      run: cargo build --release
      shell: bash
